name: Build and publish Docker image

on:
  push:
    branches: main

jobs:
  main:
    name: Build Docker image
    runs-on: archlinux-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@master
      - name: Build Chromium
        run: |
          commands=$(sed -n -e '/RUN/,$p' Dockerfile | sed 's/RUN.*//;/#.*$/d;/^$/d;s/&& \\//g;' | tr '\n' ';')
          echo "Commands to run: ${commands}"
          sudo eval $commands
      - uses: actions/upload-artifact@v2
        with:
          name: APKs
          path: /apks/