name: Build and publish Docker image

on:
  push:
    branches: main

jobs:
  main:
    name: Build and push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@master
      - name: free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
      - name: Install buildah
        run: |
          sudo apt-get install -qq -y software-properties-common
          sudo add-apt-repository -y ppa:projectatomic/ppa
          sudo apt-get update -qq
          sudo apt-get -qq -y install buildah
      - name: Build the Docker image
        run: buildah bud --format=docker --layers -f Dockerfile .